[package]
name = "vesting-base"
version = "1.1.0"
authors = ["Astroport"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all init/handle/query exports
library = []

[dependencies]
cw20 = { version = "0.15" }
cosmwasm-std = { workspace = true }
cw-storage-plus = { workspace = true }
astroport = { path = "../../packages/astroport" }
thiserror = { workspace = true }
# we keep it at 0.15 instead of latest version just for vesting investors contract
cw-utils = "0.15"
cosmwasm-schema = { workspace = true }
